### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employee/high-salary

### Он должен создавать множество новых сотрудников;
POST http://localhost:8080/employee/

### Он должен редактировать сотрудника с указанным id
PUT http://localhost:8080/employee/{id}

### Он должен возвращать информацию о сотруднике с переданным id
GET http://localhost:8080/employee/2

### Он должен удалять сотрудника с переданным id
DELETE http://localhost:8080/employee/{id}

### Он должен возвращать всех сотрудников, зарплата которых выше переданного параметра salary
GET http://localhost:8080/employee/salary/HigherThanSalary?compareSalary=88888
